# Generated by Django 4.2.7 on 2024-02-11 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 11, 1, 1, 6, 962511, tzinfo=datetime.timezone.utc)),
        ),
    ]
