# Generated by Django 4.2.7 on 2024-02-12 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followres',
            field=models.ManyToManyField(blank=True, related_name='asdnjkl', to=settings.AUTH_USER_MODEL),
        ),
    ]
