# Generated by Django 4.2.7 on 2024-02-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_alter_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='liked_users',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_users',
        ),
    ]
